### PR TITLE
Trying to enable animation but failed

### PR DESCRIPTION
**Pull request by liolop**
Hi Peli,

I have changed all global variables into local scope which is dependent on the variables values in `Board` class. However, after I did that, the animation stopped. I think it might be the function declaration issue with the variable `requestAnimFrame` but I am not sure. Could you please take a look and help me out? Thank you!

### CODE REVIEW

**Comment by pelikhan** [comment]
This is a massive change. Please provide smaller code changes to review.

**Comment by liolop** [comment]
Sorry, could you just check the one at commit number `3146a7e` if its possible?

**Comment by pelikhan** [comment]
You'll have to figure this out with the debugger.

**Comment by pelikhan** [comment]
Don't create massive pull request. Instead work incrementally with small, tested, reviewed changes. You can create many many PRs, no problem. Have massive changes like these ones make it really hard to go back in time and investigate issues.

**Comment by liolop** [comment]
Sure, thanks for your advice! As I was unfamiliar with how pull requests work, I accidentally sent a pull request with showing massive changes. But I was meant to only send the most recent change for discussing.

**Comment by pelikhan** [comment]
No worries.

**Comment by Chelseazhangx** [comment]
@pelikhan hi Peli, just a quick question on the simulator map design when you have time. I have sent you a map design on slack, which includes a 2*3 intersection map with a tilt road. However, when I implement this map design, I have trouble to draw the diagonal road, because the native code doesn't contain diagonal rendering logic. Would you mind provide some help? Right now I have a 2*4 intersections map from commit 3534f1c.

**Comment by pelikhan** [comment]
Just drop the tilt road for now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Chelseazhangx** [comment]
Thanks! We will work on the 2*4 map for now.

**Pull request merged**
